import type { Metadata } from "next";
<<<<<<< HEAD
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "hackiwha",
  description: "hackiwha 2.0",
=======
import { Geist_Mono } from "next/font/google";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MindForge",
  description: "Generated by create next app",
>>>>>>> 58dc7fab1059e77c06f0ab05a02d827f27e58002
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>
        {children}
      </body>
    </html>
  );
}

// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
=======
      <body className={` ${geistMono.variable}`}>{children}</body>
    </html>
  );
}
>>>>>>> 58dc7fab1059e77c06f0ab05a02d827f27e58002
